# In config/tasks.yaml

routing_task:
  description: >
    You are assisting a single, logged-in user. The user ID is handled automatically. **Do not ask for a user ID or any other personal identification.**

    Review the conversation history to understand the context:
    ---
    {history}
    ---
    Now, analyze the latest user query: '{query}'.
    Based on the query and the history, determine the user's intent (e.g., answering a question, applying for a loan).
    If the latest query provides information that a specialist was asking for, delegate back to that specialist.
    If the intent is clear and all information is available, delegate to the correct specialist agent to perform the action.
  expected_output: >
    A final, comprehensive response to the user. This could be a direct answer, a clarifying question from a specialist,
    or a confirmation that an action has been completed.